#ifndef STANDX_SRC_DEFINES_H_
#define STANDX_SRC_DEFINES_H_

#define DEFAULT_CONTRACT_SIZE 0.01
#define ORDER_NUM 10
#define MAX_ORDER_NUM_FACTOR 1.5
#define PRICE_ACCURACY_INT 2
#define PRICE_ACCURACY_FLOAT 0.01

#endif  // STANDX_SRC_DEFINES_H_
